name: Deploiement CD
on:
  push:
    branches :
      - master

  workflow_dispatch:

jobs:
  CD:
    name: Continuous Delivery
    runs-on: ubuntu-latest
    steps:
      - name: SSH into production server
        env:
          DIR_PROJECT: ${{secrets.PROJECT_DIR}}
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.CD_HOST}}
          username: ${{secrets.CD_USER}}
          password: ${{secrets.CD_SK}}
          port: 22
          script: |
            cd $DIR_PROJECT/Stat-Membre
            # Mise a jour du code
            git pull
            cd front-end/
            # Install dependencies
            npm install
            # Build Front 
            npm run build
            # Relancement du code back
            pm2 restart stat-back